### ISSUE TITLE
Directory Search problem with Rest backend

### ISSUE THREAD

**Issue by daobee** [kamax-io/mxisd#48]
## Expected Behavior
Im configuring a mxisd server in __Remote sessions only__ and has only __one REST backend__.
and i want to use the Directory Search feature.
if everything ok, i think my `Rest directory search endpoint` server will receive the search request.

config file:
```
rest:
  enabled: true
  host: 'http://restbackendip:port'
  endpoints:
    auth: '/_mxisd/backend/api/v1/auth/login'
    directory: '/_mxisd/backend/api/v1/directory/user/search'
    identity:
      single: '/_mxisd/backend/api/v1/identity/lookup/single'
      bulk: '/_mxisd/backend/api/v1/identity/lookup/bulk'

session:
  policy:
    validation:
      enabled: true
      forLocal:
        enabled: true
        toLocal: false
        toRemote:
          enabled: true
      forRemote:
        enabled: true
        toLocal: false
        toRemote:
          enabled: true
```

## Actual Behavior
The entrypoint got nothing. I noticed that no Directory provider was loaded when the program initing.
```
2017-12-23 21:57:55.759  INFO [           main]    i.k.m.directory.DirectoryManager : Directory providers:
2017-12-23 21:57:56.995  INFO [           main] k.m.MatrixIdentityServerApplication : Started MatrixIdentityServerApplication in 7.358 seconds (JVM running for 9.061)
```
but the providers will be load correctly if i use ldap or sql backend.

I found that there are no @Component and @Autowired in RestDirectoryProvider class unlike the LdapDirectoryProvider or the sql one. Is the intentionally?  what if i add them?

## Steps to Reproduce the Problem

  1. do the session and rest configuration
  1. start mxisd server

## Specifications

  - Version: master branch  6a5a4b3c1c15d24d2096fb0a7cb0ea5c0f441df2
  - Platform: ubuntu 16.04
  - Subsystem:
