### ISSUE TITLE
User Directory search Sending Invites

### ISSUE THREAD

**Issue by nanohayder** [kamax-io/mxisd#55]
Hi,

    first thanks for this great job it's helping us a lot.

we have a problem that when we use the User Directory (LDAP Backend) if we opened an invite with a user that doesn't have Riot installed we would like an Email to be sent to him as an invite can you please help us do that. 

Mxisd Config
```
matrix.domain: *******
key.path: /var/mxisd/sign.key
storage.provider.sqlite.database: /var/mxisd/mxisd.db

logging:
  level:
    org:
      springframework: 'WARN'
      apache:
        catalina: 'WARN'
        directory: 'WARN'

lookup:
  recursive:
    enabled: true
    allowedCidr:
      - '0.0.0.0/0'

dns.overwrite.homeserver.client:
  - name: '${matrix.domain}'
    value: 'http://localhost:8008'

ldap.enabled: true
ldap.connection.host: '*******'
ldap.connection.bindDn: 'uid=*******,cn=users,cn=accounts,dc=earthlink,dc=iq'
ldap.connection.bindPassword: '*******'
ldap.connection.baseDn: 'cn=users,cn=accounts,dc=earthlink,dc=iq'
ldap.connection.tls: false
ldap.attribute.uid.type: 'uid'
ldap.attribute.uid.value: 'uid'
ldap.attribute.name: 'cn'
ldap.attribute.threepid.email:
  - 'mail'

ldap.attribute.threepid.msisdn:
  - 'telephoneNumber'

directory.exclude.homeserever: true
```

both "Mxisd" and the "home server" is behind nginx reverse proxy
